language: android
sudo: required
jdk: oraclejdk8
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - APP_NAME="serval-project"
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
script:
- "./gradlew build connectedCheck"
before_install:
 - openssl aes-256-cbc -K $encrypted_1e0e1c84b069_key -iv $encrypted_1e0e1c84b069_iv
  -in secrets.tar.enc -out secrets.tar -d
 - tar xvf secrets.tar
before_deploy:
 - cp $TRAVIS_BUILD_DIR/.keystore $HOME
 - cd app/build/outputs/apk/
 - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/production.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk production.jks
 - jarsigner -verify app-release-unsigned.apk
 - "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk ${APP_NAME}.apk"
deploy:
  provider: releases
  file: "$APP_NAME.apk"
  skip_cleanup: true
  on:
    repo: githubUsername/Repository
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "$GITHUB_API_KEY"
